#!/Users/keith.hamilton/src/github.com/wk_rd/test/bin/python2.7

# -*- coding: utf-8 -*-
import re
import sys

from pyrowire.resources.console_scripts.pyrowire import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    print sys.argv
    #sys.exit(main())