profanity = [
    'adultxxx',
    'amateurcouples',
    'amateurhardcore',
    'amateurhousewives',
    'amateurnude',
    'amateurporn',
    'amateursex',
    'amateurxxx',
    'analcum',
    'analfuck',
    'analingus',
    'analjpg',
    'analpics',
    'analrape',
    'analraping',
    'analsex',
    'anilingus',
    'animalerotica',
    'animalsex',
    'asianass',
    'asianbabes',
    'asianbondage',
    'asianhardcore',
    'asiannude',
    'asianpics',
    'asianpleasures',
    'asianporn',
    'asianpussy',
    'asiansex',
    'asiansluts',
    'asianthumbnails',
    'asianxxx',
    'asiasex',
    'asphyxiophilia',
    'assfuck',
    'asshole',
    'assjpg',
    'asslic',
    'assphuc',
    'assphuk',
    'asspics',
    'autoerotic',
    'ballsac',
    'beasiality',
    'beastality',
    'beasteality',
    'beastial',
    'beastility',
    'beastlove',
    'beastsex',
    'beastuality',
    'beastyality',
    'beatiality',
    'beavershot',
    'bedroomcam',
    'bestiality',
    'bigblackcocks',
    'bigblacktits',
    'bigclits',
    'bigcock',
    'bigdick',
    'biggestcock',
    'bignipples',
    'bigpussy',
    'bigtit',
    'blackass',
    'blackcum',
    'blackcunt',
    'blowboy',
    'blowjob',
    'bondagepics',
    'bondagepictures',
    'bondagestories',
    'bondagevideos',
    'boner',
    'boylove',
    'buttbanger',
    'buttbanging',
    'buttfuck',
    'buttpirate',
    'buttplug',
    'buttreamer',
    'buttstuffer',
    'candyteen',
    'carpetmuncher',
    'celebnudes',
    'celebritiesnaked',
    'celebritiesnude',
    'celebritynude',
    'celebrityporn',
    'celebritysex',
    'celebsluts',
    'celebsnude',
    'chatsex',
    'chickswithdicks',
    'childporno',
    'childsex',
    'chinesepussy',
    'clit',
    'closeuppussy',
    'clubsex',
    'cock',
    'comebath',
    'comedrinkers',
    'comeeaters',
    'comefacial',
    'comeguzzlers',
    'comeshot',
    'coonass',
    'crotchless',
    'cumbath',
    'cumbucket',
    'cumcovered',
    'cumdrinkers',
    'cumeaters',
    'cumface',
    'cumfacial',
    'cumgallery',
    'cumguzzlers',
    'cumhole',
    'cuming',
    'cumload',
    'cumlovers',
    'cumqueen',
    'cums',
    'cunilingus',
    'cunnilingus',
    'cunt',
    'cybererotica',
    'cyberflix',
    'cyberlust',
    'cybernude',
    'cyberotica',
    'cyberporn',
    'cybersex',
    'cyberslut',
    'cyberteenpic',
    'dickhead',
    'dicklick',
    'dickmeat',
    'dicknasty',
    'dicksex',
    'dicksuck',
    'dildo',
    'dirtypictures',
    'dirtysex',
    'dogfuck',
    'doggiestyle',
    'doggystyle',
    'dogsex',
    'doublepenetration',
    'downblouse',
    'drippingpussy',
    'eatcum',
    'eatingcum',
    'eatingpussy',
    'eatpussy',
    'eatshit',
    'ebonyporn',
    'ebonysex',
    'ebonyxxxlinks',
    'ejaculate',
    'escortservice',
    'explicitsex',
    'extremehardcoresex',
    'extremesex',
    'facesit',
    'facialcum',
    'familysex',
    'farmgirl',
    'farmlove',
    'farmslut',
    'farmteen',
    'fatpussy',
    'fatsex',
    'fatxxx',
    'felatio',
    'fellatio',
    'feltch',
    'fingerfuck',
    'fistfuck',
    'fistin',
    'freeadultgames',
    'freeadultsex',
    'freeadultstories',
    'freebeast',
    'freeblackpics',
    'freeblacksites',
    'freedick',
    'freeerotic',
    'freefile',
    'freefuck',
    'freegay',
    'freehardcore',
    'freelesbian',
    'freelivesex',
    'freenakedwomen',
    'freenude',
    'freeoralsex',
    'freeporn',
    'freepussy',
    'freesex',
    'freesmut',
    'freeteensex',
    'freethebeast',
    'freetit',
    'freexxx',
    'frexxx',
    'fucc',
    'fuck',
    'fudgepacker',
    'fuk',
    'fvck',
    'gangbang',
    'gangrape',
    'gangraping',
    'gaybondage',
    'gayeroticstories',
    'gayhardcore',
    'gaynudes',
    'gayphotos',
    'gaypics',
    'gaypictures',
    'gayporn',
    'gaysexstories',
    'gaytwinks',
    'gayvideo',
    'gayxxx',
    'girlcam',
    'givehead',
    'gizzum',
    'gloryhole',
    'groupsex',
    'hairypussy',
    'hairywomen',
    'handjob',
    'hardcorehooters',
    'hardcorejunky',
    'hardcoremovies',
    'hardcorepics',
    'hardcorepictures',
    'hardcorepix',
    'hardcoreporn',
    'hardcorepussy',
    'hardcoresex',
    'hardcorevideo',
    'hardcorexxx',
    'harddicks',
    'hardecore',
    'hardniples',
    'hardnipples',
    'hardon',
    'hardporn',
    'hardsex',
    'harrypussy',
    'hollywoodwhores',
    'hootersex',
    'horny',
    'horseblow',
    'horsecum',
    'horsesex',
    'hotcum',
    'hotpussy',
    'hotsex',
    'hugedicks',
    'hugehooters',
    'hugemen',
    'hugenipples',
    'hugepussy',
    'hugetits',
    'illegalgirls',
    'illegalsex',
    'incestpic',
    'incestpix',
    'incestsex',
    'interracialhardcore',
    'interracialsex',
    'interracialxxx',
    'japanesebondage',
    'japaneseporn',
    'japansex',
    'jerkingoff',
    'jism',
    'jiz',
    'juicypussy',
    'kiddiepic',
    'kiddieporn',
    'kiddipix',
    'kiddiporn',
    'kidpix',
    'kidporn',
    'kidsex',
    'kike',
    'largedicks',
    'largepussy',
    'largetits',
    'latinohardcore',
    'latinonude',
    'latinoporn',
    'latinosluts',
    'legsex',
    'lesbianerotica',
    'lesbianhardcore',
    'lesbianorgies',
    'lesbianpics',
    'lesbianpictures',
    'lesbianporn',
    'littlenipples',
    'littletits',
    'liveporn',
    'livesex',
    'lolitapic',
    'lolitapix',
    'lolitasex',
    'longdicks',
    'longnipples',
    'masterbate',
    'masterbating',
    'masterbation',
    'mastrubation',
    'mastubation',
    'masturbate',
    'masturbating',
    'maturepussy',
    'maturewomennude',
    'megapussy',
    'mondoporno',
    'mpegsex',
    'muffdive',
    'nakedbabes',
    'nakedblackwomen',
    'nakedboy',
    'nakedcelebrities',
    'nakedchicks',
    'nakedchildren',
    'nakedgirl',
    'nakedkid',
    'nakedladies',
    'nakedmalecelebrities',
    'nakedmen',
    'nakedpictures',
    'nastychat',
    'nastypussy',
    'nastysex',
    'nastythumbs',
    'necrophilia',
    'negro',
    'netsex',
    'nigga',
    'nigger',
    'nudeactresses',
    'nudeasianwomen',
    'nudeblackmen',
    'nudeblackwomen',
    'nudeblondes',
    'nudeboy',
    'nudecartoons',
    'nudeceleb',
    'nudecollegegirls',
    'nudegay',
    'nudegirl',
    'nudehollywood',
    'nudeladies',
    'nudelesbians',
    'nudemalecelebrities',
    'nudemalecelebs',
    'nudemales',
    'nudemen',
    'nudeolderwomen',
    'nudephoto',
    'nudepics',
    'nudepicture',
    'nudepreteen',
    'nudepussy',
    'nudesex',
    'nudestars',
    'nudesupermodels',
    'nudeteen',
    'nudetoons',
    'nudeunderage',
    'nudevideoconferencing',
    'nudewomen',
    'oldersluts',
    'oldpussy',
    'oldsex',
    'oldsluts',
    'oralsex',
    'pantyfreek',
    'pantyhosefetish',
    'partysex',
    'peeon',
    'peepshow',
    'phonesex',
    'phreak',
    'phuc',
    'phuk',
    'picturesex',
    'picturesofsex',
    'picturessex',
    'pinkpussy',
    'porn',
    'preteen',
    'purehardcore',
    'pussie',
    'pusssy',
    'pussy',
    'raghead',
    'rapeme',
    'rapepic',
    'rapepix',
    'rawsex',
    'realhardcore',
    'realsex',
    'rimjob',
    'rimming',
    's1ut',
    'scatlover',
    'scatology',
    'scatsex',
    'screwing',
    'seekforsex',
    'sex4free',
    'sexacts',
    'sexadult',
    'sexamateur',
    'sexanal',
    'sexandpictures',
    'sexavi',
    'sexcam',
    'sexcartoon',
    'sexcenterfolds',
    'sexchat',
    'sexcites',
    'sexcity',
    'sexclips',
    'sexclub',
    'sexcomics',
    'sexfantasy',
    'sexfarm',
    'sexfiction',
    'sexfiles',
    'sexfree',
    'sexgallery',
    'sexgames',
    'sexgirls',
    'sexgrand',
    'sexhardcore',
    'sexhound',
    'sexhungry',
    'seximages',
    'sexjuice',
    'sexland',
    'sexlinks',
    'sexlinx',
    'sexlist',
    'sexlookup',
    'sexmagazine',
    'sexmags',
    'sexmodels',
    'sexmovie',
    'sexmpegs',
    'sexnet',
    'sexnewsgroups',
    'sexnude',
    'sexnudity',
    'sexonline',
    'sexoral',
    'sexparty',
    'sexpersonals',
    'sexphoto',
    'sexpic',
    'sexpix',
    'sexplanet',
    'sexplaza',
    'sexploration',
    'sexpost',
    'sexsamples',
    'sexsexsex',
    'sexshare',
    'sexshop',
    'sexshow',
    'sexsite',
    'sexslave',
    'sexsource',
    'sexspaces',
    'sexstories',
    'sexstory',
    'sexswap',
    'sextales',
    'sexteen',
    'sextoon',
    'sextoy',
    'sexualadvantage',
    'sexuales',
    'sexualfantasies',
    'sexualpictures',
    'sexualstories',
    'sexuncensored',
    'sexvideo',
    'sexvillage',
    'sexvote',
    'sexworld',
    'sexx',
    'sexysites',
    'sexysquirter',
    'sexyupskirts',
    'shaved',
    'shemalecentral',
    'shemalepics',
    'shemalepictures',
    'shemalesex',
    'shiteat',
    'shiter',
    'shites',
    'shithead',
    'shits',
    'shitting',
    'sht',
    'shyted',
    'shyter',
    'shytes',
    'shyting',
    'shyts',
    'slavesex',
    'slut',
    'smalltits',
    'smut',
    'snufffilm',
    'snuffpic',
    'snuffpix',
    'spankingavi',
    'spankinglinks',
    'spankingpictures',
    'spermfacial',
    'strapon',
    'suckin',
    'supersex',
    'supertits',
    'swedenteens',
    'swedsex',
    'teenagesex',
    'teenerotica',
    'teenplay',
    'teensex',
    'teenshave',
    'teenxxx',
    'threesomes',
    'tinytits',
    'titbags',
    'titbondage',
    'titflesh',
    'tities',
    'tits',
    'tittie',
    'titts',
    'titty',
    'tokyotopless',
    'toonsex',
    'toplesswomen',
    'twat',
    'ultrahardcore',
    'uncut',
    'underagepic',
    'underagepix',
    'underagesex',
    'upskirt',
    'urinate',
    'urinating',
    'vibrator',
    'videosex',
    'virtualsex',
    'voyeurcam',
    'voyeurdorm',
    'voyuerweb',
    'warez',
    'websex',
    'wetpanties',
    'wetsex',
    'wetspot',
    'wetvagina',
    'whore',
    'wifeswapping',
    'wildsex',
    'wwwsex',
    'xpic',
    'xrated',
    'xxpasswords',
    'xxx',
    'youngsex',
    'zooass',
    'zoophile',
    'zoophilia',
    'zoose',
    'amateur couples',
    'amateur hardcore',
    'amateur housewives',
    'amateur nude',
    'amateur nudes',
    'amateur sex',
    'anal jpg',
    'anal pics',
    'anal rape',
    'anal raping',
    'anal sex',
    'animal erotica',
    'animal sex',
    'asian ass',
    'asian babes',
    'asian bondage',
    'asian hardcore',
    'asian nude',
    'asian nudes',
    'asian pics',
    'asian pleasures',
    'asian sex',
    'asian thumbnails',
    'ass jpg',
    'ass lick',
    'ass licking',
    'ass pics',
    'ass worship',
    'bedroom cam',
    'big dick',
    'big dicks',
    'big hooters',
    'big nipples',
    'big tit',
    'black ass',
    'black asses',
    'black dick',
    'black dicks',
    'black hardcore',
    'black sex',
    'bondage pics',
    'bondage pictures',
    'bondage stories',
    'bondage videos',
    'celebrities naked',
    'celebrities nude',
    'celebrity nude',
    'celebrity nudes',
    'celebs nude',
    'chat sex',
    'chicks with dicks',
    'come bath',
    'come drinkers',
    'come eaters',
    'come facial',
    'come facials',
    'come guzzlers',
    'come shot',
    'come shots',
    'cum drinkers',
    'cum eaters',
    'cum facial',
    'cum facials',
    'cum guzzlers',
    'cum shot',
    'cum shots',
    'cyber sex',
    'dick lick',
    'dick licker',
    'dick lickers',
    'dick licking',
    'dick lickings',
    'dick licks',
    'dick meat',
    'dick nasty',
    'dick suck',
    'dick sucker',
    'dick suckers',
    'dirty pictures',
    'dirty sex',
    'double penetration',
    'down blouse',
    'ebony sex',
    'escort service',
    'escort services',
    'extreme sex',
    'face sit',
    'face sitting',
    'facial cum',
    'family sex',
    'farm girl',
    'farm girls',
    'farm teen',
    'farm teens',
    'free adult games',
    'free adult stories',
    'free black pics',
    'free erotic',
    'free gay',
    'free hardcore',
    'free lesbian',
    'free live sex',
    'free naked women',
    'free nude',
    'free nudes',
    'free oral sex',
    'free sex',
    'free tit',
    'gang bang',
    'gang bangs',
    'gang rape',
    'gang raping',
    'gay hardcore',
    'gay nudes',
    'gay photos',
    'gay pics',
    'gay pictures',
    'gay sex stories',
    'gay twinks',
    'gay video',
    'girl cams',
    'golden shower',
    'golden showers',
    'group sex',
    'hard niples',
    'hard nipples',
    'hard sex',
    'hardcore hooters',
    'hardcore pics',
    'hardcore pictures',
    'hardcore sex',
    'hardcore video',
    'hardcore videos',
    'horse blow',
    'horse cum',
    'horse sex',
    'hot cum',
    'hot sex',
    'hot stories',
    'huge dicks',
    'huge hooters',
    'huge nipples',
    'interracial hardcore',
    'interracial sex',
    'japanese bondage',
    'jerking off',
    'latino hardcore',
    'latino nude',
    'latino nudes',
    'lesbian pics',
    'lesbian pictures',
    'live sex',
    'long nipples',
    'mature women nude',
    'mpeg sex',
    'muff dive',
    'naked babes',
    'naked black women',
    'naked celebrities',
    'naked chicks',
    'naked ladies',
    'naked male celebrities',
    'naked men',
    'naked pictures',
    'naked women',
    'nasty sex',
    'nude asian women',
    'nude black men',
    'nude black women',
    'nude blondes',
    'nude cartoons',
    'nude celeb',
    'nude celebrities',
    'nude celebrity',
    'nude celebs',
    'nude college girls',
    'nude gay',
    'nude ladies',
    'nude lesbians',
    'nude male celebrities',
    'nude male celebs',
    'nude males',
    'nude older women',
    'nude photo',
    'nude photographs',
    'nude photos',
    'nude pics',
    'nude picture',
    'nude pictures',
    'nude sex',
    'nude stars',
    'nude supermodels',
    'nude toons',
    'nude video conferencing',
    'old sex',
    'oral sex',
    'panty pics',
    'panty pictures',
    'panty shots',
    'pantyhose fetish',
    'picture sex',
    'pictures of sex',
    'pictures sex',
    'raw sex',
    'sex adult',
    'sex amateur',
    'sex anal',
    'sex and pictures',
    'sex avi',
    'sex cam',
    'sex cams',
    'sex cartoon',
    'sex cartoons',
    'sex chat',
    'sex clips',
    'sex club',
    'sex clubs',
    'sex comics',
    'sex fantasy',
    'sex free',
    'sex gallery',
    'sex games',
    'sex hardcore',
    'sex images',
    'sex links',
    'sex magazine',
    'sex magazines',
    'sex movie',
    'sex movies',
    'sex mpeg',
    'sex mpegs',
    'sex newsgroups',
    'sex nude',
    'sex nudity',
    'sex oral',
    'sex personals',
    'sex photo',
    'sex photos',
    'Sex pic',
    'Sex pics',
    'Sex picture',
    'Sex pictures',
    'Sex pix',
    'sex plaza',
    'sex samples',
    'sex search',
    'sex shop',
    'sex show',
    'sex shows',
    'sex site',
    'sex sites',
    'sex slave',
    'sex slaves',
    'sex sounds',
    'sex stories',
    'sex story',
    'sex storys',
    'sex toons',
    'sex toy',
    'sex toys',
    'sex video',
    'sex videos',
    'shemale pics',
    'shemale pictures',
    'shemale sex',
    'spanking avi',
    'spanking links',
    'spanking pictures',
    'sperm facial',
    'super sex',
    'tit bags',
    'tit flesh',
    'tokyo topless',
    'topless women',
    'video sex',
    'voyeur cam',
    'voyeur web',
    'weird sex',
    'wet sex',
    'x rated',
    'x ratedmovie',
    'x ratedmovies',
    'x ratedvideo',
    'x ratedvideos',
    'Dream for Darfur',
    'Tibetan Action Network',
    'Free Tibet',
    'STAND',
    'Dream for Darfur',
    'Team for Darfur',
    'Not on Our Watch',
    'Reporters Without Borders',
    'Committee to Protect Journalists',
    'Killer Coke',
    'India Resource Center',
    'Human Rights Watch',
    'Amnesty International',
    'Human Rights in China',
    'Sudan',
    'Darfur',
    'Genocide',
    'Tibet',
    'Tibetan',
    'Xinjiang',
    'Dalai Lama',
    'Monks',
    'Human rights',
    'Deception',
    'Immorality',
    'Labor abuse',
    'Environmental abuse',
    'Human rights abuse',
    'Animal abuse',
    'Cat culling',
    'Dog culling',
    'Workplace abuses',
    'Hitler',
    'Nazi',
    'Regime',
    'Rwanda',
    'Armenia',
    'Janjaweed',
    'Union leaders',
    'Pesticides',
    'Biosolids',
    'Water depletion',
    'Kerala',
    'Colombia',
    'Killing',
    'Kill',
    'Kills',
    'Killer',
    'Murder',
    'Murders',
    'Murderer',
    'Death',
    'Dead',
    'Dying',
    'Bloodshed',
    'Blood',
    'Pollution',
    'Pollutes',
    'Boycott',
    'Ban',
    'Protest',
    'Abuse',
    'Violence',
    'Crisis',
    'Conflict',
    'Evil',
    'Corrupt',
    'Corruption',
    'Suffering',
    'Suffer',
    'Repression',
    'Repress',
    'Torture',
    'Crackdown',
    'Arrests',
    'Political prisoner',
    'Exploit',
    'Exploitation',
    'Hate'
]